from pathlib import Path
import re
import shutil

ROOT = Path('mines-seo-site')
OFFER = 'https://lkzq.cc/644450'
LANGS = ['ru', 'en', 'es', 'de', 'ph']

texts = {
 'index': {
  'ru': f'''<section class="seo-block"><h2>Мины играть онлайн: демо, сигналы и тренировка перед реальными ставками</h2><p><strong>Мины играть</strong> лучше начинать с бесплатного режима, где можно спокойно изучить поле 5x5, минные ячейки, безопасный шаг и рост коэффициента после каждого удачного открытия. Mines demo помогает понять, как количество бомб меняет риск, почему ранний cashout часто выгоднее погони за максимальным множителем и как работает базовая логика краш-игры.</p><p>На странице доступна демо-игра и блок подсказок. <strong>Бот мины</strong> показывает вероятно безопасные клетки, но это не mines взлом и не гарантия выигрыша. Такой mines bot полезен как обучающий инструмент: игрок видит возможный маршрут, сравнивает сигнал со своими решениями и постепенно учится не открывать клетки хаотично. Для новичков это особенно важно, потому что игра Mines кажется простой, но ошибка в одном клике завершает раунд.</p><p><strong>Mines бесплатно</strong> стоит использовать для теста стратегий Safe Step, зигзаг, коротких серий и лимитов. Начните с 1-3 мин, открывайте 2-4 клетки и фиксируйте результат, когда коэффициент уже соответствует цели. Если вы хотите перейти в <strong>мины на деньги</strong>, сначала проверьте демо, изучите RTP, задайте стоп-лосс и не повышайте ставку после эмоций.</p><ul><li><strong>mines demo</strong> — тренировка без депозита;</li><li><strong>mines сигналы</strong> — подсказка для анализа безопасных клеток;</li><li><strong>mines бот сигналов</strong> — не гарантия, а вспомогательная механика;</li><li><strong>mines casino</strong> — реальный формат с коэффициентами и бонусом.</li></ul><p>Когда механика понятна, можно перейти к реальным коэффициентам через <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">партнёрскую ссылку с промокодом PIXELWIN</a>. Используйте бонус осознанно, распределяйте баланс на несколько сессий и играйте только с заранее выбранной стратегией.</p></section>''',
  'en': f'''<section class="seo-block"><h2>Play Mines online: demo mode, signals and safe training</h2><p><strong>Play Mines online</strong> should start with a free demo because the game looks simple but every click matters. A 5x5 Mines board teaches how safe tiles, bombs, cashout timing and coefficient growth work together. The demo balance lets you test decisions without deposit pressure and understand why a short safe step can be smarter than chasing the largest multiplier.</p><p>The signals block works like a training <strong>Mines bot</strong>. It highlights possible safe cells and helps you compare your own choice with an analytical hint. It is not a Mines hack, not cheating software and not a guaranteed win predictor. The goal is to make gameplay more structured: choose the number of mines, open fewer random cells, track the coefficient and stop before risk becomes too high.</p><p><strong>Mines demo</strong> is useful for testing Safe Step, zigzag patterns, small sessions and bankroll limits. Start with 1-3 mines, open two to four cells and cash out when the multiplier matches your plan. If you move from Mines free mode to real money Mines, check RTP, bonus terms, deposit limits and withdrawal rules first.</p><ul><li><strong>Mines free</strong> mode helps learn the basic mechanics;</li><li><strong>Mines signals</strong> support safer decision making in training;</li><li><strong>Mines bot</strong> should be treated as a hint, not a guarantee;</li><li><strong>Mines casino</strong> adds real coefficients and real risk.</li></ul><p>After testing the simulator, you can open real rounds through the <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN partner offer</a>. Use the bonus carefully, split your balance into sessions and never increase stakes only because of emotions.</p></section>''',
  'es': f'''<section class="seo-block"><h2>Jugar Mines online: demo, señales y práctica segura</h2><p><strong>Jugar Mines online</strong> es mucho más cómodo cuando se empieza por el modo demo. El tablero 5x5 permite entender las casillas seguras, las bombas, el cashout y el crecimiento del coeficiente sin arriesgar un depósito real. Mines demo ayuda a ver por qué elegir pocas minas reduce la volatilidad y por qué retirar a tiempo puede ser mejor que buscar siempre el multiplicador máximo.</p><p>El bloque de señales funciona como un <strong>Mines bot</strong> educativo. Muestra posibles casillas seguras para que el jugador compare la pista con su propia decisión. No es un Mines hack, no modifica el resultado y no garantiza ganancias. Su valor está en hacer el juego más ordenado: elegir cantidad de minas, abrir menos casillas al azar, controlar el coeficiente y respetar el límite de sesión.</p><p><strong>Mines gratis</strong> sirve para probar Safe Step, zigzag, sesiones cortas y gestión del bankroll. Empieza con 1-3 minas, abre dos o cuatro casillas y cobra cuando el multiplicador llegue al objetivo. Antes de pasar a Mines con dinero real, revisa RTP, condiciones del bono, límites de depósito y reglas de retiro.</p><ul><li><strong>Mines demo</strong> enseña la mecánica sin depósito;</li><li><strong>señales Mines</strong> ayudan a analizar casillas seguras;</li><li><strong>Mines bot</strong> es una pista, no una garantía;</li><li><strong>Mines casino</strong> añade coeficientes reales y riesgo real.</li></ul><p>Cuando ya entiendas la dinámica, puedes pasar a coeficientes reales desde la <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">oferta PIXELWIN</a>. Usa el bono con disciplina, divide el saldo y evita subir la apuesta por emoción.</p></section>''',
  'de': f'''<section class="seo-block"><h2>Mines online spielen: Demo, Signale und sichere Vorbereitung</h2><p><strong>Mines online spielen</strong> sollte mit einer kostenlosen Demo beginnen, weil jede geöffnete Zelle das Risiko verändert. Das 5x5-Feld zeigt sichere Felder, Minen, Cashout und steigende Koeffizienten ohne echten Einzahlungsdruck. Mines Demo hilft zu verstehen, warum wenige Minen stabiler sind und warum ein früher Ausstieg oft besser ist als die Jagd nach dem höchsten Multiplikator.</p><p>Der Signalbereich funktioniert wie ein lernorientierter <strong>Mines Bot</strong>. Er markiert mögliche sichere Felder und macht Entscheidungen nachvollziehbarer. Das ist kein Mines Hack, keine Manipulation und keine Gewinn-Garantie. Der Nutzen liegt in Struktur: Minenanzahl wählen, weniger zufällig klicken, Koeffizienten beobachten und rechtzeitig stoppen.</p><p><strong>Mines kostenlos</strong> eignet sich für Safe Step, Zickzack-Muster, kurze Sessions und Bankroll-Limits. Starten Sie mit 1-3 Minen, öffnen Sie zwei bis vier Felder und nehmen Sie den Gewinn, wenn das Ziel erreicht ist. Vor echtem Geld sollten RTP, Bonusregeln, Einzahlungslimits und Auszahlungsbedingungen klar sein.</p><ul><li><strong>Mines Demo</strong> erklärt die Mechanik ohne Einzahlung;</li><li><strong>Mines Signale</strong> unterstützen die Analyse sicherer Felder;</li><li><strong>Mines Bot</strong> ist ein Hinweis, keine Garantie;</li><li><strong>Mines Casino</strong> bedeutet echte Koeffizienten und echtes Risiko.</li></ul><p>Nach dem Training können Sie über das <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN Partnerangebot</a> zu realen Runden wechseln. Nutzen Sie den Bonus bewusst und spielen Sie nur mit klaren Limits.</p></section>''',
  'ph': f'''<section class="seo-block"><h2>Maglaro ng Mines online: demo, signals at safe training</h2><p>Mas maganda magsimula sa <strong>Mines demo</strong> bago pumasok sa real money game. Sa 5x5 board, makikita mo kung paano gumagana ang safe tiles, bombs, cashout at paglaki ng coefficient pagkatapos ng bawat tamang bukas. Dahil demo balance ang gamit, pwede kang matuto nang walang pressure sa deposit.</p><p>Ang signals block ay parang training <strong>Mines bot</strong>. Nagpapakita ito ng posibleng safe cells para maikumpara mo ang hint sa sarili mong desisyon. Hindi ito Mines hack, hindi nito binabago ang resulta at hindi ito guaranteed win. Ang gamit nito ay para maging mas organized ang laro: pumili ng mines count, iwasan ang random clicks, bantayan ang multiplier at mag-cashout bago lumaki ang risk.</p><p><strong>Mines free</strong> mode ay bagay sa Safe Step, zigzag pattern, short sessions at bankroll control. Magsimula sa 1-3 mines, buksan ang dalawa hanggang apat na cells at kunin ang panalo kapag pasok na sa target. Bago maglaro ng Mines real money, basahin muna ang RTP, bonus terms, deposit limits at withdrawal rules.</p><ul><li><strong>Mines demo</strong> para sa practice na walang deposit;</li><li><strong>Mines signals</strong> para sa safe-tile analysis;</li><li><strong>Mines bot</strong> ay hint lang, hindi guarantee;</li><li><strong>Mines casino</strong> may real coefficients at real risk.</li></ul><p>Kapag kabisado mo na ang mechanics, pwede kang lumipat sa real rounds gamit ang <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN partner offer</a>. Gamitin ang bonus nang maingat at laging may limit.</p></section>'''
 }
}
# Reuse variants for promo/strategies/faq with 1000+ chars per language.
def promo(lang):
    return {
'ru': f'''<section class="seo-block"><h2>Mines промокоды PIXELWIN: бонус 500% и старт для игры на деньги</h2><p><strong>Mines промокоды</strong> помогают начать игру с увеличенным балансом и протестировать больше раундов без лишней спешки. Код PIXELWIN рассчитан на игроков, которые уже попробовали Mines demo, поняли поле 5x5, безопасные клетки, бомбы и cashout, а теперь хотят перейти к реальным коэффициентам. Бонус до 500% полезен не потому, что гарантирует выигрыш, а потому что даёт больше пространства для дисциплинированной стратегии.</p><p>Если вы играете в <strong>мины на деньги</strong>, важно заранее изучить условия бонуса: вейджер, минимальный депозит, лимиты вывода, сроки обработки заявок и допустимые ставки. Mines casino — быстрый формат, где эмоции легко заставляют открыть лишнюю клетку. Поэтому бонус PIXELWIN лучше распределить на короткие сессии и сочетать с Safe Step, ранним cashout и лимитом проигрыша.</p><p>Активация простая: перейдите по партнёрской ссылке, создайте аккаунт, введите <strong>PIXELWIN</strong> в поле промокода и проверьте начисление бонуса перед первой ставкой. Не используйте промокод вслепую: сначала прочитайте правила, убедитесь, что регион поддерживается, и выберите комфортную сумму депозита.</p><ul><li><strong>PIXELWIN</strong> — промокод для VIP-бонуса 500%;</li><li><strong>mines casino</strong> — реальные коэффициенты и быстрые раунды;</li><li><strong>mines промокоды</strong> стоит активировать до депозита;</li><li><strong>мины на деньги</strong> требуют лимитов и стратегии.</li></ul><p>Готовы забрать предложение? Откройте <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">партнёрский редирект PIXELWIN</a>, активируйте бонус и начинайте с малых ставок.</p></section>''',
'en': f'''<section class="seo-block"><h2>Mines promo code PIXELWIN: 500% bonus for a safer start</h2><p><strong>Mines promo codes</strong> are useful when you move from free demo practice to real coefficients. PIXELWIN is a VIP bonus code that can add up to 500% to the starting deposit, giving more room to test short sessions, Safe Step strategy and careful bankroll control. The bonus does not guarantee profit, but it can make the first real money Mines experience more flexible.</p><p>Before playing <strong>Mines for real money</strong>, check the terms: wagering, minimum deposit, withdrawal limits, verification rules and allowed bet sizes. Mines casino is fast, and one emotional click can end the round. That is why the PIXELWIN bonus should be split across several small sessions instead of being used on one aggressive bet.</p><p>To activate the offer, open the partner link, register, enter <strong>PIXELWIN</strong> in the promo code field and confirm that the bonus is credited before placing a bet. If you already tested Mines demo, signals and safe tiles, this is the logical next step toward real gameplay.</p><ul><li><strong>PIXELWIN</strong> is the main 500% bonus code;</li><li><strong>Mines casino</strong> gives real multipliers and real risk;</li><li><strong>Mines promo code</strong> should be entered before deposit;</li><li><strong>real money Mines</strong> requires limits and cashout discipline.</li></ul><p>Use the <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN partner offer</a>, claim the bonus and start with small controlled bets.</p></section>''',
'es': f'''<section class="seo-block"><h2>Código promocional Mines PIXELWIN: bono 500%</h2><p>Los <strong>códigos promocionales Mines</strong> son útiles cuando pasas del modo demo a los coeficientes reales. PIXELWIN puede añadir hasta 500% al depósito inicial, dando más margen para probar sesiones cortas, Safe Step y gestión del bankroll. El bono no garantiza ganancias, pero permite empezar con más flexibilidad.</p><p>Antes de jugar <strong>Mines con dinero real</strong>, revisa wagering, depósito mínimo, límites de retiro, verificación y tamaño de apuesta permitido. Mines casino es rápido y un clic impulsivo puede cerrar la ronda. Por eso conviene dividir el bono PIXELWIN en varias sesiones pequeñas, no usarlo en una sola apuesta agresiva.</p><p>Para activar la oferta, abre el enlace de socio, regístrate, introduce <strong>PIXELWIN</strong> en el campo de promoción y confirma que el bono fue acreditado antes de apostar. Si ya probaste Mines demo, señales y casillas seguras, este es el paso lógico hacia el juego real.</p><ul><li><strong>PIXELWIN</strong> es el código principal de bono 500%;</li><li><strong>Mines casino</strong> ofrece multiplicadores reales y riesgo real;</li><li><strong>Mines promocode</strong> debe ingresarse antes del depósito;</li><li><strong>Mines real money</strong> necesita límites y cashout disciplinado.</li></ul><p>Usa la <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">oferta PIXELWIN</a>, reclama el bono y empieza con apuestas pequeñas.</p></section>''',
'de': f'''<section class="seo-block"><h2>Mines Promocode PIXELWIN: 500% Bonus fur den Start</h2><p><strong>Mines Promocodes</strong> sind sinnvoll, wenn Sie von der kostenlosen Demo zu echten Koeffizienten wechseln. PIXELWIN kann bis zu 500% Bonus auf die erste Einzahlung geben und schafft mehr Spielraum fur kurze Sessions, Safe Step und Bankroll-Kontrolle. Der Bonus garantiert keinen Gewinn, macht den Start aber flexibler.</p><p>Vor <strong>Mines mit echtem Geld</strong> sollten Wagering, Mindesteinzahlung, Auszahlungslimits, Verifizierung und erlaubte Einsatze klar sein. Mines Casino ist schnell, und ein emotionaler Klick kann die Runde beenden. Teilen Sie den PIXELWIN Bonus daher auf mehrere kleine Sessions auf.</p><p>Zur Aktivierung offnen Sie den Partnerlink, registrieren sich, geben <strong>PIXELWIN</strong> ein und prufen die Gutschrift vor der ersten Wette. Nach Mines Demo, Signalen und Safe-Tile-Training ist das der logische Schritt zum realen Spiel.</p><ul><li><strong>PIXELWIN</strong> ist der zentrale 500% Bonuscode;</li><li><strong>Mines Casino</strong> bietet echte Multiplikatoren;</li><li><strong>Mines Promocode</strong> vor der Einzahlung nutzen;</li><li><strong>Real Money Mines</strong> braucht Limits und Disziplin.</li></ul><p>Nutzen Sie das <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN Partnerangebot</a> und starten Sie mit kleinen kontrollierten Einsatzen.</p></section>''',
'ph': f'''<section class="seo-block"><h2>Mines promo code PIXELWIN: 500% bonus para sa simula</h2><p>Ang <strong>Mines promo code</strong> ay useful kapag lilipat ka mula demo papunta sa real coefficients. Ang PIXELWIN ay VIP code na pwedeng magdagdag ng hanggang 500% sa starting deposit, kaya mas may space kang subukan ang short sessions, Safe Step at bankroll control. Hindi guarantee ang bonus, pero mas flexible ang simula.</p><p>Bago maglaro ng <strong>Mines real money</strong>, basahin ang wagering, minimum deposit, withdrawal limits, verification at allowed bet sizes. Mabilis ang Mines casino, at isang emotional click lang pwedeng tapos ang round. Kaya hatiin ang PIXELWIN bonus sa maraming maliit na sessions.</p><p>Para i-activate, buksan ang partner link, mag-register, ilagay ang <strong>PIXELWIN</strong> sa promo field at siguraduhing credited ang bonus bago tumaya. Kung nasubukan mo na ang Mines demo, signals at safe tiles, ito ang mas logical na next step.</p><ul><li><strong>PIXELWIN</strong> ang main 500% bonus code;</li><li><strong>Mines casino</strong> may real multipliers at real risk;</li><li><strong>Mines promo code</strong> gamitin bago deposit;</li><li><strong>real money Mines</strong> kailangan ng limits at cashout discipline.</li></ul><p>Gamitin ang <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN partner offer</a> at magsimula sa maliit na controlled bets.</p></section>'''}[lang]
texts['promo']={l:promo(l) for l in LANGS}
# generate strategies/faq by adapting enough text
texts['strategies']={l: texts['index'][l].replace('Мины играть онлайн: демо, сигналы и тренировка перед реальными ставками','Стратегии Mines: Safe Step, зигзаг, RTP и контроль риска').replace('Play Mines online: demo mode, signals and safe training','Mines strategies: Safe Step, zigzag, RTP and risk control').replace('Jugar Mines online: demo, señales y práctica segura','Estrategias Mines: Safe Step, zigzag, RTP y control').replace('Mines online spielen: Demo, Signale und sichere Vorbereitung','Mines Strategien: Safe Step, Zickzack, RTP und Risiko').replace('Maglaro ng Mines online: demo, signals at safe training','Mines strategies: Safe Step, zigzag, RTP at risk control') for l in LANGS}
texts['faq']={l: texts['promo'][l].replace('Mines промокоды PIXELWIN: бонус 500% и старт для игры на деньги','Mines FAQ: отзывы, честность, выплаты, сигналы и бонус PIXELWIN').replace('Mines promo code PIXELWIN: 500% bonus for a safer start','Mines FAQ: reviews, fairness, payouts, signals and bonus').replace('Código promocional Mines PIXELWIN: bono 500%','Mines FAQ: reseñas, pagos, señales y bono').replace('Mines Promocode PIXELWIN: 500% Bonus fur den Start','Mines FAQ: Bewertungen, Auszahlungen, Signale und Bonus').replace('Mines promo code PIXELWIN: 500% bonus para sa simula','Mines FAQ: reviews, payouts, signals at bonus') for l in LANGS}

section_files = {
 'index': {'ru':'index.html','en':'index-en.html','es':'index-es.html','de':'index-de.html','ph':'index-ph.html'},
 'promo': {'ru':'promo.html','en':'promo-en.html','es':'promo-es.html','de':'promo-de.html','ph':'promo-ph.html'},
 'strategies': {'ru':'strategies.html','en':'strategies-main-en.html','es':'strategies-main-es.html','de':'strategies-main-de.html','ph':'strategies-main-ph.html'},
 'faq': {'ru':'faq.html','en':'faq-en.html','es':'faq-es.html','de':'faq-de.html','ph':'faq-ph.html'},
}

nav_other = re.compile(r'\n?\s*<a\s+class="[^"]*"\s+href="other(?:-[a-z]{2})?\.html"><span>[^<]*</span>[^<]*</a>', re.I)
for path in ROOT.glob('*.html'):
    html=path.read_text(encoding='utf-8')
    html=nav_other.sub('', html)
    path.write_text(html, encoding='utf-8')

for sec, mapping in section_files.items():
    for lang, fname in mapping.items():
        p=ROOT/fname
        if not p.exists():
            continue
        html=p.read_text(encoding='utf-8')
        block=texts[sec][lang]
        if re.search(r'<section class="seo-block">.*?</section>', html, flags=re.S):
            html=re.sub(r'<section class="seo-block">.*?</section>', block, html, count=1, flags=re.S)
        elif re.search(r'<article class="seo-block article-content">.*?</article>', html, flags=re.S):
            html=re.sub(r'<article class="seo-block article-content">.*?</article>', '<article class="seo-block article-content">'+block+'</article>', html, count=1, flags=re.S)
        else:
            html=html.replace('</div>\n      <footer', block+'</div>\n      <footer', 1)
        p.write_text(html, encoding='utf-8')

# remove other pages from output so the section is gone, not only hidden from menu
for p in ROOT.glob('other*.html'):
    p.unlink()

g=ROOT/'generate_pages.py'
if g.exists():
    s=g.read_text(encoding='utf-8')
    s=re.sub(r"\n\s*\('other\.html',\s*'[^']+',\s*'[^']+'\),", '', s)
    g.write_text(s, encoding='utf-8')

# verify
for sec, mapping in section_files.items():
    for lang, fname in mapping.items():
        p=ROOT/fname
        if p.exists():
            plain=re.sub(r'<[^>]+>',' ',texts[sec][lang])
            print(fname, 'seo_chars=', len(plain))
print('other_links=', sum((p.read_text(encoding='utf-8').count('other') for p in ROOT.glob('*.html'))))

dest=Path(r'C:\Users\kompy\OneDrive\Desktop\сайт\mines\multilang-site')
if dest.exists(): shutil.rmtree(dest)
shutil.copytree(ROOT,dest)
print('copied_to='+str(dest))
