from pathlib import Path
import re
import shutil

ROOT = Path('mines-seo-site')
OFFER = 'https://lkzq.cc/644450'

GUIDES = {
    'apk.html': {
        'lang': 'ru',
        'cards': '''<section class="apk-guide">
  <div class="apk-guide-card apk-feature"><span class="apk-symbol">✦</span><h2>Что выбрать: APK или PWA?</h2><p><strong>PWA</strong> — самый быстрый и безопасный вариант: сайт добавляется на главный экран, открывается как приложение и не требует установки неизвестного файла. <strong>APK</strong> используйте только если файл доступен внутри официального аккаунта казино.</p></div>
  <div class="apk-guide-card"><span class="apk-symbol">①</span><h2>Android Chrome</h2><ol><li>Откройте страницу Mines в Chrome.</li><li>Нажмите меню <strong>⋮</strong> в правом верхнем углу.</li><li>Выберите <strong>«Установить приложение»</strong> или <strong>«Добавить на главный экран»</strong>.</li><li>Подтвердите установку и запустите иконку Mines с рабочего стола.</li></ol></div>
  <div class="apk-guide-card"><span class="apk-symbol">②</span><h2>iPhone Safari</h2><ol><li>Откройте сайт именно в Safari, не во встроенном браузере мессенджера.</li><li>Нажмите кнопку <strong>«Поделиться»</strong>.</li><li>Выберите <strong>«На экран Домой»</strong>.</li><li>Переименуйте ярлык, например MinesNeon, и нажмите <strong>«Добавить»</strong>.</li></ol></div>
  <div class="apk-guide-card apk-note"><span class="apk-symbol">◆</span><h2>Проверка безопасности</h2><ul><li>Не скачивайте APK из Telegram, форумов и случайных зеркал.</li><li>Проверяйте домен, HTTPS и наличие личного кабинета.</li><li>Не вводите пароль в копиях сайта и подозрительных pop-up окнах.</li><li>После установки протестируйте demo, сигналы и промокод PIXELWIN.</li></ul></div>
</section>''',
        'seo': f'''<section class="seo-block apk-seo"><h2>Подробный гайд: как mines скачать на телефон и не ошибиться</h2><p><strong>Mines скачать</strong> можно двумя способами: через PWA-ярлык или через APK-файл. Для большинства игроков лучше подходит PWA, потому что установка проходит прямо из браузера, не требует разрешения на неизвестные источники и удобно работает на Android и iPhone. Вы получаете быстрый доступ к Mines demo, сигналам, странице бонуса PIXELWIN и FAQ без поиска сайта в истории браузера.</p><p>Если вы используете Android, открывайте страницу в Chrome и выбирайте установку приложения из меню. Если у вас iPhone, используйте Safari и функцию «На экран Домой». После этого иконка Mines появится рядом с обычными приложениями, а интерфейс будет открываться почти как нативная программа. Это удобно для игроков, которые часто проверяют mines сигналы, тренируются в демо или хотят быстро перейти к промокоду.</p><p><strong>APK Mines</strong> стоит скачивать осторожно. Никогда не устанавливайте файл из случайных источников: поддельный APK может украсть пароль, заменить платёжную страницу или показывать фальшивые бонусы. Безопасный сценарий — перейти через <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">партнёрскую ссылку PIXELWIN</a>, зарегистрироваться, проверить официальный кабинет и только там искать раздел загрузки приложения.</p><ul><li>✦ PWA — быстрый вариант без неизвестных файлов;</li><li>◆ APK — только из официального кабинета;</li><li>✓ перед депозитом проверьте demo, RTP, сигналы и правила бонуса;</li><li>❖ используйте PIXELWIN до пополнения баланса.</li></ul><p>Такой подход помогает установить Mines аккуратно, сохранить доступ к аккаунту и начать игру на реальные коэффициенты без лишнего риска.</p></section>'''
    },
    'apk-en.html': {
        'lang': 'en',
        'cards': '''<section class="apk-guide">
  <div class="apk-guide-card apk-feature"><span class="apk-symbol">✦</span><h2>APK or PWA: what should you install?</h2><p><strong>PWA</strong> is the safest quick option: the site is added to the home screen and opens like an app without downloading an unknown file. Use <strong>APK</strong> only when the download is available inside the official casino account.</p></div>
  <div class="apk-guide-card"><span class="apk-symbol">①</span><h2>Android Chrome</h2><ol><li>Open the Mines page in Chrome.</li><li>Tap the <strong>⋮</strong> menu in the top right corner.</li><li>Select <strong>Install app</strong> or <strong>Add to Home screen</strong>.</li><li>Confirm and launch Mines from the new icon.</li></ol></div>
  <div class="apk-guide-card"><span class="apk-symbol">②</span><h2>iPhone Safari</h2><ol><li>Open the page in Safari, not inside a messenger browser.</li><li>Tap the <strong>Share</strong> button.</li><li>Choose <strong>Add to Home Screen</strong>.</li><li>Name the shortcut MinesNeon and tap <strong>Add</strong>.</li></ol></div>
  <div class="apk-guide-card apk-note"><span class="apk-symbol">◆</span><h2>Safety checklist</h2><ul><li>Do not download APK files from Telegram, forums or random mirrors.</li><li>Check HTTPS, the domain and the account area.</li><li>Never enter your password in suspicious copies or pop-ups.</li><li>After installation, test demo, signals and PIXELWIN bonus.</li></ul></div>
</section>''',
        'seo': f'''<section class="seo-block apk-seo"><h2>Detailed guide: how to download Mines safely on mobile</h2><p><strong>Download Mines</strong> can mean two different things: installing a PWA shortcut or downloading an APK file. For most users, PWA is the better first choice because it works directly from the browser, does not require unknown-source permissions and is comfortable on Android and iPhone. You still get fast access to Mines demo, signals, the PIXELWIN bonus page and FAQ.</p><p>On Android, open the page in Chrome and use the install option in the browser menu. On iPhone, open Safari and use Add to Home Screen. The Mines icon will appear next to normal apps, and the page will launch almost like a native mobile application. This is useful if you often check Mines signals, train safe tiles in demo mode or want quick access to the promo code before deposit.</p><p><strong>Mines APK</strong> should be handled carefully. Never install files from random mirrors: a fake APK can steal login data, replace payment pages or show fake bonuses. The safer path is to open the <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN partner offer</a>, register, check the official account area and download only from there if an APK option exists.</p><ul><li>✦ PWA is fast and avoids unknown files;</li><li>◆ APK should come only from the official account;</li><li>✓ test demo, RTP, signals and bonus rules first;</li><li>❖ activate PIXELWIN before making a deposit.</li></ul><p>This approach keeps the installation simple, protects the account and makes the move to real coefficients more controlled.</p></section>'''
    },
    'apk-es.html': {
        'lang': 'es',
        'cards': '''<section class="apk-guide">
  <div class="apk-guide-card apk-feature"><span class="apk-symbol">✦</span><h2>APK o PWA: ¿qué conviene instalar?</h2><p><strong>PWA</strong> es la opción rápida y segura: el sitio se añade a la pantalla de inicio y se abre como una app sin descargar archivos desconocidos. Usa <strong>APK</strong> solo si está disponible dentro de la cuenta oficial del casino.</p></div>
  <div class="apk-guide-card"><span class="apk-symbol">①</span><h2>Android Chrome</h2><ol><li>Abre la página Mines en Chrome.</li><li>Toca el menú <strong>⋮</strong>.</li><li>Elige <strong>Instalar aplicación</strong> o <strong>Añadir a pantalla de inicio</strong>.</li><li>Confirma y abre Mines desde el nuevo icono.</li></ol></div>
  <div class="apk-guide-card"><span class="apk-symbol">②</span><h2>iPhone Safari</h2><ol><li>Abre el sitio en Safari, no en el navegador de una app.</li><li>Toca <strong>Compartir</strong>.</li><li>Selecciona <strong>Añadir a pantalla de inicio</strong>.</li><li>Guarda el acceso con el nombre MinesNeon.</li></ol></div>
  <div class="apk-guide-card apk-note"><span class="apk-symbol">◆</span><h2>Checklist de seguridad</h2><ul><li>No descargues APK desde Telegram, foros o mirrors aleatorios.</li><li>Verifica HTTPS, dominio y área de cuenta.</li><li>No escribas tu contraseña en copias sospechosas.</li><li>Después instala demo, señales y bono PIXELWIN.</li></ul></div>
</section>''',
        'seo': f'''<section class="seo-block apk-seo"><h2>Guía detallada: cómo descargar Mines en móvil de forma segura</h2><p><strong>Descargar Mines</strong> puede significar instalar un acceso PWA o bajar un archivo APK. Para la mayoría de jugadores, PWA es la primera opción porque funciona desde el navegador, no exige permisos de fuentes desconocidas y es cómodo en Android y iPhone. Aun así tendrás acceso rápido a Mines demo, señales, página del bono PIXELWIN y FAQ.</p><p>En Android, abre la página en Chrome y usa la opción de instalación del menú. En iPhone, entra desde Safari y pulsa Añadir a pantalla de inicio. El icono de Mines aparecerá junto a tus aplicaciones normales y abrirá el sitio casi como una app nativa. Es ideal si revisas señales Mines, practicas casillas seguras en demo o quieres llegar rápido al código promocional.</p><p><strong>Mines APK</strong> debe manejarse con cuidado. Un archivo falso puede robar datos, cambiar páginas de pago o mostrar bonos inexistentes. La ruta más segura es entrar por la <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">oferta PIXELWIN</a>, registrarte, revisar el área oficial de cuenta y descargar solo desde allí si existe opción APK.</p><ul><li>✦ PWA evita archivos desconocidos;</li><li>◆ APK solo desde cuenta oficial;</li><li>✓ prueba demo, RTP, señales y reglas del bono;</li><li>❖ activa PIXELWIN antes del depósito.</li></ul><p>Así la instalación es clara, la cuenta queda más protegida y el paso a coeficientes reales se hace con menos riesgo.</p></section>'''
    },
    'apk-de.html': {
        'lang': 'de',
        'cards': '''<section class="apk-guide">
  <div class="apk-guide-card apk-feature"><span class="apk-symbol">✦</span><h2>APK oder PWA: was ist besser?</h2><p><strong>PWA</strong> ist die schnelle und sichere Variante: Die Seite wird zum Startbildschirm hinzugefügt und öffnet sich wie eine App, ohne unbekannte Datei. <strong>APK</strong> nur nutzen, wenn der Download im offiziellen Casino-Konto verfügbar ist.</p></div>
  <div class="apk-guide-card"><span class="apk-symbol">①</span><h2>Android Chrome</h2><ol><li>Öffnen Sie Mines in Chrome.</li><li>Tippen Sie auf das Menü <strong>⋮</strong>.</li><li>Wählen Sie <strong>App installieren</strong> oder <strong>Zum Startbildschirm</strong>.</li><li>Bestätigen und starten Sie Mines über das Icon.</li></ol></div>
  <div class="apk-guide-card"><span class="apk-symbol">②</span><h2>iPhone Safari</h2><ol><li>Öffnen Sie die Seite in Safari.</li><li>Tippen Sie auf <strong>Teilen</strong>.</li><li>Wählen Sie <strong>Zum Home-Bildschirm</strong>.</li><li>Speichern Sie die Verknüpfung als MinesNeon.</li></ol></div>
  <div class="apk-guide-card apk-note"><span class="apk-symbol">◆</span><h2>Sicherheitscheck</h2><ul><li>Keine APKs aus Telegram, Foren oder zufälligen Mirrors laden.</li><li>HTTPS, Domain und Kontobereich prüfen.</li><li>Passwort nie in verdächtigen Kopien eingeben.</li><li>Nach Installation Demo, Signale und PIXELWIN testen.</li></ul></div>
</section>''',
        'seo': f'''<section class="seo-block apk-seo"><h2>Ausführliche Anleitung: Mines sicher auf dem Handy installieren</h2><p><strong>Mines herunterladen</strong> bedeutet entweder PWA-Verknüpfung installieren oder eine APK-Datei laden. Für die meisten Nutzer ist PWA die bessere erste Wahl, weil sie direkt aus dem Browser funktioniert, keine unbekannten Quellen benötigt und auf Android sowie iPhone bequem ist. Demo, Signale, PIXELWIN Bonus und FAQ bleiben schnell erreichbar.</p><p>Auf Android öffnen Sie Chrome und wählen die Installationsoption im Menü. Auf iPhone nutzen Sie Safari und Zum Home-Bildschirm. Danach erscheint das Mines Icon wie eine normale App. Das ist praktisch, wenn Sie Mines Signale prüfen, sichere Felder in der Demo trainieren oder den Promocode schnell öffnen möchten.</p><p><strong>Mines APK</strong> muss vorsichtig behandelt werden. Eine gefälschte Datei kann Logins stehlen, Zahlungsseiten ersetzen oder falsche Boni anzeigen. Sicherer ist der Weg über das <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN Partnerangebot</a>, Registrierung und Download nur aus dem offiziellen Kontobereich.</p><ul><li>✦ PWA ist schnell und ohne unbekannte Datei;</li><li>◆ APK nur aus offiziellem Konto;</li><li>✓ zuerst Demo, RTP, Signale und Bonusregeln prüfen;</li><li>❖ PIXELWIN vor Einzahlung aktivieren.</li></ul><p>So bleibt die Installation verständlich, das Konto geschützter und der Wechsel zu echten Koeffizienten kontrollierter.</p></section>'''
    },
    'apk-ph.html': {
        'lang': 'ph',
        'cards': '''<section class="apk-guide">
  <div class="apk-guide-card apk-feature"><span class="apk-symbol">✦</span><h2>APK o PWA: alin ang mas okay?</h2><p><strong>PWA</strong> ang pinaka-simple at safe: idadagdag ang site sa home screen at bubukas na parang app, walang unknown file. Gamitin lang ang <strong>APK</strong> kung nasa official casino account ang download.</p></div>
  <div class="apk-guide-card"><span class="apk-symbol">①</span><h2>Android Chrome</h2><ol><li>Buksan ang Mines page sa Chrome.</li><li>I-tap ang menu <strong>⋮</strong>.</li><li>Piliin ang <strong>Install app</strong> o <strong>Add to Home screen</strong>.</li><li>I-confirm at buksan ang Mines icon.</li></ol></div>
  <div class="apk-guide-card"><span class="apk-symbol">②</span><h2>iPhone Safari</h2><ol><li>Buksan ang site sa Safari.</li><li>I-tap ang <strong>Share</strong>.</li><li>Piliin ang <strong>Add to Home Screen</strong>.</li><li>I-save ang shortcut bilang MinesNeon.</li></ol></div>
  <div class="apk-guide-card apk-note"><span class="apk-symbol">◆</span><h2>Safety checklist</h2><ul><li>Huwag mag-download ng APK sa Telegram, forums o random mirrors.</li><li>I-check ang HTTPS, domain at account area.</li><li>Huwag maglagay ng password sa suspicious copies.</li><li>Pagkatapos, subukan ang demo, signals at PIXELWIN bonus.</li></ul></div>
</section>''',
        'seo': f'''<section class="seo-block apk-seo"><h2>Detalyadong guide: paano i-download ang Mines sa mobile nang safe</h2><p>Ang <strong>Mines download</strong> ay pwedeng PWA shortcut o APK file. Para sa karamihan, mas okay muna ang PWA dahil gumagana ito mula browser, hindi kailangan ng unknown-source permission at komportable sa Android at iPhone. Mabilis mo pa ring mabubuksan ang Mines demo, signals, PIXELWIN bonus page at FAQ.</p><p>Sa Android, buksan sa Chrome at piliin ang install option sa menu. Sa iPhone, gamitin ang Safari at Add to Home Screen. Lalabas ang Mines icon katabi ng normal apps at bubukas ito halos parang native app. Useful ito kung madalas kang tumingin ng Mines signals, mag-practice ng safe tiles sa demo o buksan ang promo code bago deposit.</p><p>Ang <strong>Mines APK</strong> dapat ingatan. Ang fake APK ay pwedeng magnakaw ng login, palitan ang payment page o magpakita ng pekeng bonus. Mas safe ang ruta: buksan ang <a href="{OFFER}" rel="nofollow sponsored noopener" target="_blank">PIXELWIN partner offer</a>, mag-register, i-check ang official account area at doon lang mag-download kung may APK option.</p><ul><li>✦ PWA ay mabilis at walang unknown file;</li><li>◆ APK dapat galing official account lang;</li><li>✓ subukan muna ang demo, RTP, signals at bonus rules;</li><li>❖ i-activate ang PIXELWIN bago deposit.</li></ul><p>Sa ganitong paraan, malinaw ang installation, mas protected ang account at mas controlled ang paglipat sa real coefficients.</p></section>'''
    }
}

for filename, data in GUIDES.items():
    path = ROOT / filename
    html = path.read_text(encoding='utf-8')
    html = re.sub(r'<section class="cards install-cards">.*?</section>', data['cards'], html, count=1, flags=re.S)
    html = re.sub(r'<section class="seo-block">.*?</section>', data['seo'], html, count=1, flags=re.S)
    path.write_text(html, encoding='utf-8')

css_path = ROOT / 'assets' / 'style.css'
css = css_path.read_text(encoding='utf-8')
css_block = r'''

/* Detailed APK/PWA guide */
.apk-guide{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin:0 0 20px}
.apk-guide-card{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:var(--radius-xl);padding:24px;background:linear-gradient(180deg,rgba(255,255,255,.055),rgba(255,255,255,.025)),linear-gradient(145deg,rgba(17,28,51,.94),rgba(10,16,31,.94));box-shadow:var(--shadow),inset 0 1px 0 rgba(255,255,255,.065)}
.apk-guide-card::after{content:"";position:absolute;right:-70px;top:-70px;width:170px;height:170px;border-radius:999px;background:radial-gradient(circle,rgba(84,240,193,.15),transparent 68%);pointer-events:none}.apk-guide-card h2{padding-right:48px}.apk-symbol{position:absolute;right:18px;top:18px;display:grid;place-items:center;width:42px;height:42px;border-radius:16px;color:#06101d;background:linear-gradient(135deg,#5cf0c3,#6ee7f9 52%,#9a8cff);font-weight:1000;box-shadow:0 14px 28px rgba(84,240,193,.18)}.apk-guide-card ol,.apk-guide-card ul{margin:12px 0 0;padding-left:22px}.apk-guide-card li{margin:9px 0;color:#d8e1ef}.apk-feature{grid-column:1/-1}.apk-note{border-color:rgba(255,209,102,.22);background:linear-gradient(145deg,rgba(255,209,102,.10),rgba(17,28,51,.92))}.apk-seo ul{list-style:none;padding-left:0}.apk-seo li{position:relative;padding:10px 12px;margin:8px 0;border:1px solid rgba(226,232,240,.10);border-radius:14px;background:rgba(255,255,255,.035)}
@media (max-width:760px){.apk-guide{grid-template-columns:1fr;gap:14px}.apk-guide-card{padding:18px;border-radius:22px}.apk-symbol{width:38px;height:38px;right:14px;top:14px}.apk-guide-card h2{padding-right:42px}}
'''
if '/* Detailed APK/PWA guide */' not in css:
    css_path.write_text(css.rstrip() + css_block + '\n', encoding='utf-8')

# Keep final copy updated.
dest = Path(r'C:\Users\kompy\OneDrive\Desktop\сайт\mines\multilang-site')
if dest.exists():
    shutil.rmtree(dest)
shutil.copytree(ROOT, dest)

for filename in GUIDES:
    html = (ROOT / filename).read_text(encoding='utf-8')
    text = re.sub(r'<[^>]+>', ' ', html)
    print(filename, 'apk_guide=', 'apk-guide' in html, 'apk_chars=', len(text))
print('copied_to=' + str(dest))
